FROM python:3-alpine
ENV TARGETARCH="linux-musl-x64"

RUN apk add sudo \
    && adduser -h /home/agent -s /bin/bash -D agent \
    && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel \
    && adduser agent wheel \
    && echo -n 'agent:agent' | chpasswd

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash curl gcc git icu-libs jq musl-dev python3-dev libffi-dev openssl-dev cargo make \
        python3 \
        py3-pip \
        docker-cli \
        zip \
        nano

# Install Azure CLI
RUN pip3 install --upgrade pip \
    && pip3 install --no-cache-dir azure-cli \
    && rm -rf /var/cache/apk/*

WORKDIR /azp/

COPY ./start.sh ./
RUN chmod +x ./start.sh \
    && chown -R agent:agent /azp

USER agent

# Another option is to run the agent as root.
# ENV AGENT_ALLOW_RUNASROOT="true"

ENTRYPOINT [ "./start.sh" ]