FROM ubuntu:24.04
ENV TARGETARCH="linux-x64"
# Also can be "linux-arm", "linux-arm64".

RUN apt update \
    && apt upgrade -y \
    && apt install -y sudo curl git jq libicu74 unzip python3 python3-pip docker.io \
    && rm -rf /var/lib/apt/lists/*

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

WORKDIR /azp/
COPY ./start.sh ./

# Create agent user and set up home directory
RUN useradd -m -d /home/agent agent -s /bin/bash \
    && chown -R agent:agent /azp /home/agent \
    && echo 'agent ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/agent \
    && chmod 0440 /etc/sudoers.d/agent

RUN chmod +x ./start.sh \
    && chown -R agent:agent /azp

USER agent
# Another option is to run the agent as root.
# ENV AGENT_ALLOW_RUNASROOT="true"

ENTRYPOINT [ "./start.sh" ]