name: 'dockerBuild-$(Date:yyyy-MM-dd)$(Rev:.r)'

trigger:
  paths: 
    include:
      - push-dockerfile.yml

variables:
  image_name: "alakaganaguathoork/azure-pipelines-agent"
  image_tag: "latest"
  docker_hub_repo: "alakaganaguathoork/azure-pipelines-agent" 
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  name: "Local"

resources:
  containers:
  - container: dockerhub
    type: DockerRegistry
    image: $(image_name):$(image_tag)
    connection: docker-hub-connector

stages:
  - stage: DockerImageBuildAndPush
    displayName: Build and push Docker image
    jobs:
      - job: DockerBuildPush
        steps:
          - task: Docker@2
            name: DockerLogin
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: docker-hub-connector
              repository: $(docker_hub_repo)
          
          - task: Docker@2
            name: DockerBuildImage
            displayName: Build Docker image
            inputs:
              buildContext: .
              command: build
              containerRegistry: docker-hub-connector
              repository: $(docker_hub_repo)
              dockerfile: ./Dockerfile-alpine
              tags: $(image_tag)
            condition:
               eq(variables.isMain, true))

          - task: Docker@2
            name: DockerBuildImage
            displayName: Build Docker image
            inputs:
              buildContext: .
              command: build
              containerRegistry: docker-hub-connector
              repository: $(docker_hub_repo)
              dockerfile: ./Dockerfile-ubuntu
              tags: $(image_tag)
            condition:
               eq(variables.isMain, false))
          
          - task: Docker@2
            name: DockerPushImage
            displayName: Push Docker image to Docker Hub
            inputs:
              command: push
              containerRegistry: docker-hub-connector
              repository: $(docker_hub_repo)
              tags: $(image_tag)
              

